### ISSUE TITLE
Milestone #1

### ISSUE THREAD

**Issue by friendofdog** [cc17-alien/alien#1]
- [x] Map that shows locations of game objects as icons
  - [x] Objectives as game objects (Os and Xs)
  - [x] Player as game object
  - [x] Alien as game object
- [x] GPS tracking reflected in map
- [x] Grid-based map
- [x] Game rooms/sessions
  - [x] Room creation and player management
- [x] Alien visible using "motion detector" mechanic
- [x] "Noise" is a game construct that the Alien is attracted to
  - [x] Alien finds shortest distance straight line to noise
  - [x] Pushing the motion sensor/objective causes noise
- [x] Mobile deployed
