### ISSUE TITLE
Milestone #2

### ISSUE THREAD

**Issue by friendofdog** [cc17-alien/alien#30]
- Multiplayer
  - [x] Game is playable by multiple users at the same time
  - [x] Host can initiate game with generated ID
  - [x] Guests can join with ID
- Game scene
  - [x] Objectives outside viewable area are indicated by arrows
  - [x] Visual indication or vibration when alien is close
  - [x] Sprites for player, alien, objectives
- Noise mechanic
  - [x] Noise increases with player movement, proportional to move speed
  - [x] Noise decreases over time
- Gameover
  - [x] An ending screen will display when game ends
  - [x] Option to replay game or go to title screen
