### ISSUE TITLE
Presentation for milestone #2

### ISSUE THREAD

**Issue by friendofdog** [cc17-alien/alien#49]
- [x] Good start in terms of flow
- [x] All speakers sound professional and prepared. Very pleased with their delivery. +1
- [x] Slides are a bit bare, acceptable for first rehearsal, but not second +1
- [x] The cursor and menu bar keeps popping up—any way of minimizing that happening?
  - Not really, as far as I know - Dustin
- [x] Good covering of Dom so far.
- [ ] Mai, you need to maintain eye contact with the audience. The audience does not feel like you are talking to them but rather its like you are reading a script
- [x] Punctuation in slides should be consistent
  - Capitalization should also be consistent
- [ ] Are we suspending disbelief with the Unity editor standing in for the real emulated game? I’m not sure if this is the public facing version.
- [ ] In unity, if you do not need to show your GUI’s please maximize the game screen +1
- [x] Nice suspense tap and hold mechanic, although the UI is very basic
- [x] The concept of noise was not properly explained. I think we should suggest changing it for a more idiosyncratic word
- [x] The demo should have been first before the Unity editor part.
- [x] Please add visuals for Yoko’s CI/CD part. It will be a very interesting and beneficial part if given proper highlight
- [x] The slides in general are very basic, they would be much better with unique visuals or graphic theme—virtually no branding at this point.
- [x] The Technologies slide could use some clean up. Without listening, I would like to know what photon and mapbox’s role in your project.
- [x] Product Development Flow - image layout/size needs work on this slide (they seem randomly placed)
- [x] Product Development Flow - rather than bullet points, I suggest animations and visuals. This helps avoid block text
- [x] Product Development Flow - “constant meetings” does not have a good connotation. I suggest something more like coordinated sync ups or coordinated communication efforts.
- [x] Prefer team info on ending slide
- [x] The future features slide, I didn’t catch it, why was it skipped? you were still in time.
- [x] Time: 14:19 - good timeboxing!
- [x] Collapse unused/unnecessary panels in the Unity editor
