### ISSUE TITLE
Milestones #3

### ISSUE THREAD

**Issue by friendofdog** [cc17-alien/alien#60]
Multiplayer

- [x] Game start and game over scenes work with multiplayer
- [x] Global state for objectives

UI

- [x] UI resembled motion detector
- [x] Using appropriate fonts

Deployment

- [x] Latest working version of game on Google Play
